### ISSUE TITLE
Fehler in replaceInsertTag

### ISSUE THREAD

**Issue by BugBuster1701** [syncgw/contao-spambot#2]
Wenn der Tag nicht der eigene ist,  muss mit return false abgebrochen werden, sonst wird jeder Insert Tag von jeder Erweiterung die in der Reihenfolge danach registriert ist durch diese mit '' ersetzt.

https://github.com/syncgw/contao-spambot/blob/master/src/Module/SpamBotMod.php#L59
Hier muss `return false; ` hin.

**Comment by syncgw** [comment]
This mail box is not monitored and you will not get any response to your mail!

Best regards,
your ***@***.*** team
https://www.syncgw.com

Diese Mail-Box wird nicht überwacht und Sie werden auf Ihre Mail keine Antwort erhalten!

Mit freundlichen Grüßen,
Ihr ***@***.*** Team
https://www.syncgw.com

**Comment by syncgw** [comment]
fixed

**Comment by fiedsch** [comment]
Not completely fixed. die Funktion gibt nun zwar false zurück, aber der Return Type ist noch `string`, was dann nicht zu einem `return false` passt.

**Comment by syncgw** [comment]
Ei Ei EI, da waren die Finger schneller als das Hirn. Danke für den Hinweis!
