### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by raynor84** [syncgw/contao-spambot#4]
Hi,

This Module would give a great asset for one of our clients and maybe to many other contao users. 
Unfortunately I don't know how to configure it correctly. At the moment I'm trying to configure the IP-Protection.

It would be great for me and other Users to have some screenshots , on how to set it up basically for beginners. I think more Users could profit from it and it would make your Extension more prominent with all the benefits that it brings to you. 

I tried to access the page with a standard browser and a tor browser. Unfortunately the Results are the same on both browsers either if I set to much settings they both fail, or they both pass. So I don't know how it would result with a real Spammer. 

Kind Regards and Happy new Year

Stefan

**Comment by syncgw** [comment]
Hi Stefan,
thank you for your suggestions. We've already put some information about testing into the README.md file. A detailed HOWTO would exceed the capacities we want to spend on this extension.
